### ISSUE TITLE
error: exportArchive: "JiangNanMall.app" requires a provisioning profile.

### ISSUE THREAD

**Issue by GlimmeringIdeas** [AgoniNemo/Auto-IPA#1]
Error Domain=IDEProvisioningErrorDomain Code=9 ""xxxxx.app" requires a provisioning profile." UserInfo={NSLocalizedDescription="xxxxxx.app" requires a provisioning profile., NSLocalizedRecoverySuggestion=Add a profile to the "provisioningProfiles" dictionary in your Export Options property list.}

**Comment by AgoniNemo** [comment]
不好意思  最近比较忙  现在才看到  这个问题是生成的配置文件缺少参数引起的  已经更新脚本  用最新的脚本试试

**Comment by AgoniNemo** [comment]
如果新版本没有解决，请再次开启
